# Generated by Django 4.1 on 2022-08-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['ustvarjeno']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='naslov',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='opravljeno',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='uporabnik',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='ustvarjeno',
        ),
    ]
