# Generated by Django 4.1 on 2022-08-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_options_rename_title_task_naslov_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='uporabnik',
        ),
    ]
